spring:
  cassandra:
    contact-points: 52.88.35.70  # Cassandra ?????
    port: 9042                 # Cassandra ??
    keyspace-name: ad_click_db  # ?????Keyspace???
    local-datacenter: datacenter1  # ???????? (????)
    schema-action: recreate # ?????????

  kafka:
    bootstrap-servers: 52.88.35.70:9092
    consumer:
      group-id: "kafka-service-group"
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      concurrency: 3
server:
  port: 8003

